# Generated by Django 5.2.11 on 2026-02-09 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('emoji', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('temp_weight', models.FloatField(default=0.2)),
                ('wind_weight', models.FloatField(default=0.15)),
                ('rain_weight', models.FloatField(default=0.2)),
                ('uv_weight', models.FloatField(default=0.1)),
                ('humidity_weight', models.FloatField(default=0.1)),
                ('visibility_weight', models.FloatField(default=0.05)),
                ('air_quality_weight', models.FloatField(default=0.1)),
                ('golden_hour_weight', models.FloatField(default=0.0)),
                ('swell_weight', models.FloatField(default=0.0)),
                ('ideal_temp_min', models.FloatField(default=10)),
                ('ideal_temp_max', models.FloatField(default=25)),
                ('max_wind_speed', models.FloatField(default=30)),
                ('max_rain_probability', models.FloatField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideal_temp_min', models.FloatField(blank=True, null=True)),
                ('ideal_temp_max', models.FloatField(blank=True, null=True)),
                ('max_wind_speed', models.FloatField(blank=True, null=True)),
                ('max_rain_probability', models.FloatField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='activities.activitytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user activities',
                'unique_together': {('user', 'activity_type')},
            },
        ),
    ]
