# Generated by Django 5.2.11 on 2026-02-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='icon_name',
            field=models.CharField(default='activity', help_text='Lucide icon name for display', max_length=40),
        ),
    ]
